repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: stable
    hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-ast
    - id: check-json
    - id: check-merge-conflict
    - id: check-xml
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: mixed-line-ending
      args: ['--fix=auto']

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: stable
    hooks:
      - id: isort
        name: isort (python)



