name: Tests

on:
  push:
    paths:
      - src/**
      - tests/**
      - .github/**

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update coverage badge
      working-directory: .
      run: |
        touch assets/test.txt
