name: Status update

on:
  push:
    paths:
      - src/**
      - tests/**
      - .github/**

  coverage:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Update coverage badge
      run: |
        python -m pip install --upgrade pip
        pip install coverage-badge
    - name: Commit changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

        git add assets/coverage.svg
        git commit -m "update coverage badge"
        git push
