name: Tests

on:
  push:
    paths:
      - src/**
      - tests/**
      - .github/**

jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update coverage badge
      run: |
        touch assets/test.txt
    - name: Commit changes
      run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

          git add assets/test.txt
          git commit -m "create file"
          git push
